services:
  db:
    image: postgres:14
    container_name: foodgram-db
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: foodgram-db
    ports:
      - "9002:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ../backend
    container_name: foodgram-backend
    restart: always
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost
      - POSTGRES_DB=foodgram-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
    volumes:
      - ../backend:/app
      - static:/app/staticfiles
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000"

  frontend:
    container_name: foodgram-frontend
    build: ../frontend
    restart: always
    volumes:
      - ../frontend:/app/result_build/

  proxy:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - ../backend/media:/app/media
      - static:/staticfiles/
    depends_on:
      - backend

volumes:
  postgres_data:
  static:
